baseURL = "http://localhost:1313/"
languageCode = "en"
defaultContentLanguage = "en"

theme = "congo"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]